### ISSUE TITLE
Attribution to Astroship

### ISSUE THREAD

**Issue by surjithctly** [Gr33nW33n/nuxtship-template#2]
Hey, thanks for making the nuxt version of Astroship Template. Could you please add proper attribution in the Readme as well? 

Please link back to the original Astroship Template and our Website Web3Templates. Please describe where it's Forked from.

Thank you

**Comment by Gr33nW33n** [comment]
Hello, thanks for your work on the Astroship Template.

I added an Attributions section.

BR Jakob
