### ISSUE TITLE
Is it compatible with Nuxt Color Mode?

### ISSUE THREAD

**Issue by ChenZhongPu** [Gr33nW33n/nuxtship-template#3]
I followed the intruction of [Nuxt Color Mode](https://color-mode.nuxtjs.org/#nuxt-color-mode) to set up dark mode.

`nuxt.config.ts`:

```ts
export default defineNuxtConfig({
  devtools: { enabled: true },
  css: ["~/assets/css/main.css"],
  postcss: {
    plugins: {
      tailwindcss: {},
      autoprefixer: {},
    },
  },
  modules: ["nuxt-icon", '@nuxtjs/color-mode'],
});
```

And I tried to fort it be dark mode in `app.vue`:

```ts
<script>
definePageMeta({
  colorMode: 'dark',
})
</script>
```

Although class `dark-mode` is shown in <html> tag, it does not work as expected. No dark, only light still.

What else should I do?

**Comment by Gr33nW33n** [comment]
Hello,

i think you have to add the css you want to apply when the class is set, for example:

`<style>
body {
  background-color: #fff;
  color: rgba(0,0,0,0.8);
}
.dark-mode body {
  background-color: #091a28;
  color: #ebf4f1;
}
.sepia-mode body {
  background-color: #f1e7d0;
  color: #433422;
}
</style>`
